### ISSUE TITLE
Few issues related to the build instructions

### ISSUE THREAD

**Issue by h3xstream** [ovea-deprecated/jetty-session-redis#1]
**1 - The parent dependency need to be install**

https://github.com/Ovea/ovea-pom

**2 - Minor typo**

jetty-session-redis => **cd** jetty-session-redis

*_3 -The version of the parent pom should be 3 *_
    <groupId>com.ovea</groupId>
    <artifactId>ovea</artifactId>
    <version>3-SNAPSHOT</version>
    <packaging>pom</packaging>

**4 - The JBoss repository could be bundle in the pom.xml in order to find the deprecated package "trove:trove-2.1.1"**

```
<repositories>
<repository>
  <id>jboss-public-repository-group</id>
  <name>JBoss Public Repository Group</name>
  <url>https://repository.jboss.org/nexus/content/repositories/deprecated/</url>
  <layout>default</layout>
  <releases>
    <enabled>true</enabled>
    <updatePolicy>never</updatePolicy>
  </releases>
  <snapshots>
    <enabled>true</enabled>
    <updatePolicy>never</updatePolicy>
  </snapshots>
</repository>
</repositories>
```

**Comment by mathieucarbou** [comment]
Hi,

Thank you !

2 is corrected. For 3 and 4, the current code is OK. You cannot add any repo to a POM when deploying in maven central repo.

We are deploying in OSS Sonatype repo at

https://oss.sonatype.org/content/repositories/releases/com/ovea/

You can find all our lib there. These repositories are to be put in the settings.xml file.

The issue is that the oss repo should be synced with Maven Central Repo for com.ovea.\* but I see this is not the case...

**Comment by mathieucarbou** [comment]
For trove, it is available from OSS sonatype repos:

You can search it there: https://oss.sonatype.org/

**Comment by altus34** [comment]
The OSS repo is now synchronized

http://repo2.maven.org/maven2/com/ovea/
